/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/_docs/route'
import { Route as DocsIndexRouteImport } from './routes/_docs/index'
import { Route as DocsTextInputRouteRouteImport } from './routes/_docs/text-input/route'
import { Route as DocsSelectInputRouteRouteImport } from './routes/_docs/select-input/route'
import { Route as DocsSelectRouteRouteImport } from './routes/_docs/select/route'
import { Route as DocsFormRouteRouteImport } from './routes/_docs/form/route'
import { Route as DocsButtonRouteRouteImport } from './routes/_docs/button/route'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsTextInputRouteRoute = DocsTextInputRouteRouteImport.update({
  id: '/text-input',
  path: '/text-input',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSelectInputRouteRoute = DocsSelectInputRouteRouteImport.update({
  id: '/select-input',
  path: '/select-input',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSelectRouteRoute = DocsSelectRouteRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFormRouteRoute = DocsFormRouteRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsButtonRouteRoute = DocsButtonRouteRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DocsIndexRoute
  '/button': typeof DocsButtonRouteRoute
  '/form': typeof DocsFormRouteRoute
  '/select': typeof DocsSelectRouteRoute
  '/select-input': typeof DocsSelectInputRouteRoute
  '/text-input': typeof DocsTextInputRouteRoute
}
export interface FileRoutesByTo {
  '/button': typeof DocsButtonRouteRoute
  '/form': typeof DocsFormRouteRoute
  '/select': typeof DocsSelectRouteRoute
  '/select-input': typeof DocsSelectInputRouteRoute
  '/text-input': typeof DocsTextInputRouteRoute
  '/': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_docs': typeof DocsRouteRouteWithChildren
  '/_docs/button': typeof DocsButtonRouteRoute
  '/_docs/form': typeof DocsFormRouteRoute
  '/_docs/select': typeof DocsSelectRouteRoute
  '/_docs/select-input': typeof DocsSelectInputRouteRoute
  '/_docs/text-input': typeof DocsTextInputRouteRoute
  '/_docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/button'
    | '/form'
    | '/select'
    | '/select-input'
    | '/text-input'
  fileRoutesByTo: FileRoutesByTo
  to: '/button' | '/form' | '/select' | '/select-input' | '/text-input' | '/'
  id:
    | '__root__'
    | '/_docs'
    | '/_docs/button'
    | '/_docs/form'
    | '/_docs/select'
    | '/_docs/select-input'
    | '/_docs/text-input'
    | '/_docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/': {
      id: '/_docs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/text-input': {
      id: '/_docs/text-input'
      path: '/text-input'
      fullPath: '/text-input'
      preLoaderRoute: typeof DocsTextInputRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/select-input': {
      id: '/_docs/select-input'
      path: '/select-input'
      fullPath: '/select-input'
      preLoaderRoute: typeof DocsSelectInputRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/select': {
      id: '/_docs/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof DocsSelectRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/form': {
      id: '/_docs/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof DocsFormRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/button': {
      id: '/_docs/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof DocsButtonRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsButtonRouteRoute: typeof DocsButtonRouteRoute
  DocsFormRouteRoute: typeof DocsFormRouteRoute
  DocsSelectRouteRoute: typeof DocsSelectRouteRoute
  DocsSelectInputRouteRoute: typeof DocsSelectInputRouteRoute
  DocsTextInputRouteRoute: typeof DocsTextInputRouteRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsButtonRouteRoute: DocsButtonRouteRoute,
  DocsFormRouteRoute: DocsFormRouteRoute,
  DocsSelectRouteRoute: DocsSelectRouteRoute,
  DocsSelectInputRouteRoute: DocsSelectInputRouteRoute,
  DocsTextInputRouteRoute: DocsTextInputRouteRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DocsRouteRoute: DocsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
