/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/_docs/route'
import { Route as DocsIndexRouteImport } from './routes/_docs/index'
import { Route as DocsTextInputRouteRouteImport } from './routes/_docs/text-input/route'
import { Route as DocsSwitchRouteRouteImport } from './routes/_docs/switch/route'
import { Route as DocsSelectInputRouteRouteImport } from './routes/_docs/select-input/route'
import { Route as DocsSelectRouteRouteImport } from './routes/_docs/select/route'
import { Route as DocsPopoverRouteRouteImport } from './routes/_docs/popover/route'
import { Route as DocsMultiSelectInputRouteRouteImport } from './routes/_docs/multi-select-input/route'
import { Route as DocsFormRouteRouteImport } from './routes/_docs/form/route'
import { Route as DocsCheckboxRouteRouteImport } from './routes/_docs/checkbox/route'
import { Route as DocsButtonRouteRouteImport } from './routes/_docs/button/route'
import { Route as DocsBadgeRouteRouteImport } from './routes/_docs/badge/route'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsTextInputRouteRoute = DocsTextInputRouteRouteImport.update({
  id: '/text-input',
  path: '/text-input',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSwitchRouteRoute = DocsSwitchRouteRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSelectInputRouteRoute = DocsSelectInputRouteRouteImport.update({
  id: '/select-input',
  path: '/select-input',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSelectRouteRoute = DocsSelectRouteRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPopoverRouteRoute = DocsPopoverRouteRouteImport.update({
  id: '/popover',
  path: '/popover',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsMultiSelectInputRouteRoute =
  DocsMultiSelectInputRouteRouteImport.update({
    id: '/multi-select-input',
    path: '/multi-select-input',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsFormRouteRoute = DocsFormRouteRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsCheckboxRouteRoute = DocsCheckboxRouteRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsButtonRouteRoute = DocsButtonRouteRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsBadgeRouteRoute = DocsBadgeRouteRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DocsIndexRoute
  '/badge': typeof DocsBadgeRouteRoute
  '/button': typeof DocsButtonRouteRoute
  '/checkbox': typeof DocsCheckboxRouteRoute
  '/form': typeof DocsFormRouteRoute
  '/multi-select-input': typeof DocsMultiSelectInputRouteRoute
  '/popover': typeof DocsPopoverRouteRoute
  '/select': typeof DocsSelectRouteRoute
  '/select-input': typeof DocsSelectInputRouteRoute
  '/switch': typeof DocsSwitchRouteRoute
  '/text-input': typeof DocsTextInputRouteRoute
}
export interface FileRoutesByTo {
  '/badge': typeof DocsBadgeRouteRoute
  '/button': typeof DocsButtonRouteRoute
  '/checkbox': typeof DocsCheckboxRouteRoute
  '/form': typeof DocsFormRouteRoute
  '/multi-select-input': typeof DocsMultiSelectInputRouteRoute
  '/popover': typeof DocsPopoverRouteRoute
  '/select': typeof DocsSelectRouteRoute
  '/select-input': typeof DocsSelectInputRouteRoute
  '/switch': typeof DocsSwitchRouteRoute
  '/text-input': typeof DocsTextInputRouteRoute
  '/': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_docs': typeof DocsRouteRouteWithChildren
  '/_docs/badge': typeof DocsBadgeRouteRoute
  '/_docs/button': typeof DocsButtonRouteRoute
  '/_docs/checkbox': typeof DocsCheckboxRouteRoute
  '/_docs/form': typeof DocsFormRouteRoute
  '/_docs/multi-select-input': typeof DocsMultiSelectInputRouteRoute
  '/_docs/popover': typeof DocsPopoverRouteRoute
  '/_docs/select': typeof DocsSelectRouteRoute
  '/_docs/select-input': typeof DocsSelectInputRouteRoute
  '/_docs/switch': typeof DocsSwitchRouteRoute
  '/_docs/text-input': typeof DocsTextInputRouteRoute
  '/_docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badge'
    | '/button'
    | '/checkbox'
    | '/form'
    | '/multi-select-input'
    | '/popover'
    | '/select'
    | '/select-input'
    | '/switch'
    | '/text-input'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/badge'
    | '/button'
    | '/checkbox'
    | '/form'
    | '/multi-select-input'
    | '/popover'
    | '/select'
    | '/select-input'
    | '/switch'
    | '/text-input'
    | '/'
  id:
    | '__root__'
    | '/_docs'
    | '/_docs/badge'
    | '/_docs/button'
    | '/_docs/checkbox'
    | '/_docs/form'
    | '/_docs/multi-select-input'
    | '/_docs/popover'
    | '/_docs/select'
    | '/_docs/select-input'
    | '/_docs/switch'
    | '/_docs/text-input'
    | '/_docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/': {
      id: '/_docs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/text-input': {
      id: '/_docs/text-input'
      path: '/text-input'
      fullPath: '/text-input'
      preLoaderRoute: typeof DocsTextInputRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/switch': {
      id: '/_docs/switch'
      path: '/switch'
      fullPath: '/switch'
      preLoaderRoute: typeof DocsSwitchRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/select-input': {
      id: '/_docs/select-input'
      path: '/select-input'
      fullPath: '/select-input'
      preLoaderRoute: typeof DocsSelectInputRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/select': {
      id: '/_docs/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof DocsSelectRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/popover': {
      id: '/_docs/popover'
      path: '/popover'
      fullPath: '/popover'
      preLoaderRoute: typeof DocsPopoverRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/multi-select-input': {
      id: '/_docs/multi-select-input'
      path: '/multi-select-input'
      fullPath: '/multi-select-input'
      preLoaderRoute: typeof DocsMultiSelectInputRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/form': {
      id: '/_docs/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof DocsFormRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/checkbox': {
      id: '/_docs/checkbox'
      path: '/checkbox'
      fullPath: '/checkbox'
      preLoaderRoute: typeof DocsCheckboxRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/button': {
      id: '/_docs/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof DocsButtonRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/badge': {
      id: '/_docs/badge'
      path: '/badge'
      fullPath: '/badge'
      preLoaderRoute: typeof DocsBadgeRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsBadgeRouteRoute: typeof DocsBadgeRouteRoute
  DocsButtonRouteRoute: typeof DocsButtonRouteRoute
  DocsCheckboxRouteRoute: typeof DocsCheckboxRouteRoute
  DocsFormRouteRoute: typeof DocsFormRouteRoute
  DocsMultiSelectInputRouteRoute: typeof DocsMultiSelectInputRouteRoute
  DocsPopoverRouteRoute: typeof DocsPopoverRouteRoute
  DocsSelectRouteRoute: typeof DocsSelectRouteRoute
  DocsSelectInputRouteRoute: typeof DocsSelectInputRouteRoute
  DocsSwitchRouteRoute: typeof DocsSwitchRouteRoute
  DocsTextInputRouteRoute: typeof DocsTextInputRouteRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsBadgeRouteRoute: DocsBadgeRouteRoute,
  DocsButtonRouteRoute: DocsButtonRouteRoute,
  DocsCheckboxRouteRoute: DocsCheckboxRouteRoute,
  DocsFormRouteRoute: DocsFormRouteRoute,
  DocsMultiSelectInputRouteRoute: DocsMultiSelectInputRouteRoute,
  DocsPopoverRouteRoute: DocsPopoverRouteRoute,
  DocsSelectRouteRoute: DocsSelectRouteRoute,
  DocsSelectInputRouteRoute: DocsSelectInputRouteRoute,
  DocsSwitchRouteRoute: DocsSwitchRouteRoute,
  DocsTextInputRouteRoute: DocsTextInputRouteRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DocsRouteRoute: DocsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
